services:
  app:
    image: php:8.1-fpm
    container_name: magento_app
    working_dir: /var/www/html
    volumes:
      - ./magento:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - magento_network
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  web:
    image: nginx:latest
    container_name: magento_web
    volumes:
      - ./magento:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - magento_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: magento_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - magento_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: magento_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - magento_network
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  db_data:

networks:
  magento_network:
    driver: bridge
